[package]
name = "beitraege"
version = "0.1.0"
edition = "2024"

[dependencies]
gdal = { version = "0.17.1", features = ["bindgen"] }
geo = "0.29.3"
image = "0.25.5"
minifb = "0.27.0"
palette = "0.7.6"
zip = "2.4.2"


